name: Get Flag

on:
  push:
    branches:
      - main

jobs:
  get-flag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Retrieve Flag
        run: |
          aws ssm get-parameter --name trust-me --region us-west-2
