name: AWS Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::451269540766:role/t_rodman
          aws-region: us-west-2
          web-identity-token: ${{ secrets.TOKEN }}
          audience: sts.amazonaws.com

      - name: Access Flagged Resource
        run: |
          flag_value=$(aws ssm get-parameter --name trust-me --region us-west-2 --with-decryption --query "Parameter.Value" --output text)
          echo "The flag value is: $flag_value"
